language: php
php:
  - 7.1

install:
  - composer install --no-interaction
  - composer require php-coveralls/php-coveralls:^1
script:
  - php vendor/bin/phpunit -c core/phpunit.xml.dist --testsuite unit --exclude-group legacy,test --coverage-clover clover.xml

after_success:
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - php vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash)
