language: php
php:
  - 7.1

install:
  - composer install --no-interaction
  - composer require php-coveralls/php-coveralls:^1
script:
  - php vendor/bin/phpunit -c core/phpunit.xml.dist --testsuite unit --group system --coverage-clover clover.xml

after_success:
  - php vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash)
