language: php
php:
  - 7.1

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php composer.phar require php-coveralls/php-coveralls:^1
script:
  - php vendor/bin/phpunit -c core/phpunit.xml.dist --testsuite unit --group system --coverage-clover clover.xml

after_success:
  - php vendor/bin/coveralls -v
  - bash <(curl -s https://codecov.io/bash)
